#pragma once

#include "CoreMinimal.h"
#include "ETFT_ChampionList.generated.h"

UENUM(BlueprintType)
enum class ETFT_ChampionKey : uint8
{
	Garen	UMETA(DisplayName = "Garen"),
	Graves	UMETA(DisplayName = "Graves"),
	Nidalee UMETA(DisplayName = "Nidalee"),
	Darius 	UMETA(DisplayName = "Darius"),
	Mordekaiser UMETA(DisplayName = "Mordekaiser"),
	Vayne 	UMETA(DisplayName = "Vayne"),
	Elise 	UMETA(DisplayName = "Elise"),
	Warwick UMETA(DisplayName = "Warwick"),
	Camille	UMETA(DisplayName = "Camille"),
	Kassadin UMETA(DisplayName = "Kassadin"),
	KhaZix UMETA(DisplayName = "KhaZix"),
	Tristana UMETA(DisplayName = "Tristana"),
	Fiora 	UMETA(DisplayName = "Fiora"),
	RekSai  UMETA(DisplayName = "RekSai"),
	Lucian  UMETA(DisplayName = "Lucian"),
	Lulu 	UMETA(DisplayName = "Lulu"),
	Lissandra  UMETA(DisplayName = "Lissandra"),
	Varus UMETA(DisplayName = "Varus"),
	Braum UMETA(DisplayName = "Braum"),
	Blitzcrank UMETA(DisplayName = "Blitzcrank"),
	Shen UMETA(DisplayName = "Shen"),
	Ahri UMETA(DisplayName = "Ahri"),
	Zed  UMETA(DisplayName = "Zed"),
	Jayce UMETA(DisplayName = "Jayce"),
	TwistedFate  UMETA(DisplayName = "TwistedFate"),
	Pyke UMETA(DisplayName = "Pyke"),
	Gangplank UMETA(DisplayName = "Gangplank"),
	Rengar UMETA(DisplayName = "Rengar"),
	Morgana UMETA(DisplayName = "Morgana"),
	Vi  UMETA(DisplayName = "Vi"),
	Veigar  UMETA(DisplayName = "Veigar"),
	Volibear UMETA(DisplayName = "Volibear"),
	Poppy UMETA(DisplayName = "Poppy"),
	Shyvana  UMETA(DisplayName = "Shyvana"),
	Aatrox  UMETA(DisplayName = "Aatrox"),
	Ashe   UMETA(DisplayName = "Ashe"),
	Evelyn  UMETA(DisplayName = "Evelyn"),
	Katarina  UMETA(DisplayName = "Katarina"),
	Kennen  UMETA(DisplayName = "Kennen"),
	Gnar UMETA(DisplayName = "Gnar"),
	Draven UMETA(DisplayName = "Draven"),
	Leona UMETA(DisplayName = "Leona"),
	Brand UMETA(DisplayName = "Brand"),
	Sejuani UMETA(DisplayName = "Sejuani"),
	AurelionSol UMETA(DisplayName = "AurelionSol"),
	Akali  UMETA(DisplayName = "Akali"),
	Jinx  UMETA(DisplayName = "Jinx"),
	ChoGath UMETA(DisplayName = "ChoGath"),
	Kindred UMETA(DisplayName = "Kindred"),
	MissFortune  UMETA(DisplayName = "MissFortune"),
	Swain UMETA(DisplayName = "Swain"),
	Anivia UMETA(DisplayName = "Anivia"),
	Yasuo UMETA(DisplayName = "Yasuo"),
	Karthus UMETA(DisplayName = "Karthus"),
	KaiSa UMETA(DisplayName = "KaiSa"),
	Kayle UMETA(DisplayName = "Kayle"),
	Pantheon UMETA(DisplayName = "Pantheon"),
	ScuttleCrab UMETA(DisplayName = "ScuttleCrab"),
};
